project_name: kubectl-htpasswd
builds:
  - ldflags:
      - "-s -w"
      - "-extldflags=-zrelro"
      - "-extldflags=-znow"
      - "-X github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/cli.tag={{.Version}}"
      - "-X github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/cli.commit={{.FullCommit}}"
      - "-X github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/cli.date={{.CommitDate}}"
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
      - "GOFLAGS=-mod=readonly -trimpath"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/kubectl-htpasswd
archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: "false"
    format: tar.gz
    files:
      - LICENSE
source:
  enabled: true
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args: ["sign-blob", "--output-signature=${signature}", "--output-certificate=${certificate}", "${artifact}"]
    artifacts: all
